feat: Add KAFKA mocking
microcks/microcks-testcontainers-dotnet pull request #13
Opened 2024-12-05 12:07 UTC by SebastienDegodez

# Pull Request

## Proposed Changes

The goal of this enhancement is to add KAFKA support to the `testcontainers` module.

For the moment, AsynchronousAPI mocking are not supported. This feature would rique an additionnal container `microcks-async-minion`.

## Readiness Checklist

### Author/Contributor

- [ ] If documentation is needed for this change, has that been included in this pull request
- [ ] run `dotnet test` and ensure you have test coverage for the lines you are introducing
- [ ] run `dotnet husky run` and fix any issues that you have introduced

### Reviewer

- [ ] Label as either `feature`, `fix`, `documentation`, `enhancement`, `maintenance` or `breaking`

2024-12-05 12:15 UTC, SebastienDegodez commented
In JAVA, @lbroudoux  introduce a notion `MicrocksContainersEnsemble`.
An ensemble allows you to configure and controle the multiple containers with one line.
It's a good choice to increase a developper experience.

But this approach use testcontainer lifecycle `Startable`, i don't see the similar usage in .NET.

2024-12-06 11:39 UTC, lbroudoux commented
> In JAVA, @lbroudoux introduce a notion `MicrocksContainersEnsemble`. An ensemble allows you to configure and controle the multiple containers with one line. It's a good choice to increase a developper experience.
> 
> But this approach use testcontainer lifecycle `Startable`, i don't see the similar usage in .NET.

Yes, this approach was quite convenient in Java (and necessary to integrate with frameworks like Spring that can manage the testcontainers lifecycle). However it  is typically not available in other Testcontainers bindings like Node or Go.

I think it's nice to keep this notion of `MicrocksContainersEnsemble` being different from a single `MicrocksContainer` and allowing reuse of this one + wrapping the other needed container. Also, I think it's important to stick with the idioms of each language/platform and thus the `MicrocksContainersEnsemble` would have its own `ContainerBuilder` while implementing `DockerContainer` even if - behind the scenes - it manages multiple containers. What do you think?

2024-12-12 20:34 UTC, SebastienDegodez commented
https://github.com/testcontainers/testcontainers-dotnet/issues/1314

2024-12-16 16:51 UTC, lbroudoux commented
> Contribution to add network on Kafka: [testcontainers/testcontainers-dotnet#1316](https://github.com/testcontainers/testcontainers-dotnet/pull/1316)

Hey @SebastienDegodez! I had the same issue with Kafka module on testcontainers Go unfortunately...

2024-12-16 22:28 UTC, SebastienDegodez commented
> > Contribution to add network on Kafka: [testcontainers/testcontainers-dotnet#1316](https://github.com/testcontainers/testcontainers-dotnet/pull/1316)
> 
> Hey @SebastienDegodez! I had the same issue with Kafka module on testcontainers Go unfortunately...

Hey, I have develop the feature in the train this morning. For the moment, i replace the kafka_listener, protocole and advertised (in startupCallback).

2024-12-19 11:30 UTC, SebastienDegodez commented
Hello @lbroudoux , "sonar.token is invalid"

I don't understand. We have lost a secret ?

2024-12-19 14:54 UTC, lbroudoux commented
> Hello @lbroudoux , "sonar.token is invalid"
> 
> I don't understand. We have lost a secret ?

I've checked and `SONAR_TOKEN` is still declared in configuration.

It is used here: https://github.com/microcks/microcks-testcontainers-dotnet/blob/main/.github/workflows/steps.dotnet-build-test.yml#L67

2024-12-20 22:42 UTC, SebastienDegodez commented
> > Hello @lbroudoux , "sonar.token is invalid"
> > 
> > I don't understand. We have lost a secret ?
> 
> I've checked and `SONAR_TOKEN` is still declared in configuration.
> 
> It is used here: https://github.com/microcks/microcks-testcontainers-dotnet/blob/main/.github/workflows/steps.dotnet-build-test.yml#L67
> 
> I think the issue you get is because the build is happening on your own branch (your fork) and not on the Microcks one. In that case, the secret we defined is not available. Maybe we should add an additional condition to prevent trying to launch the Sonar analysis? Will check this.

I can have a condition but to follow Sonar for all pr, it's not practical. For the future, do you think it is possible to add me the right to create and push only the branch in feature/* without risk for other repo or the main branch (or another strategy) ?

2025-01-06 16:58 UTC, lbroudoux commented
Hey there! Sorry but I have been away from the keyboard due to vacations 😉 
I'm now back to work and ready to start reviewing this on tomorrow!

2025-01-06 17:52 UTC, SebastienDegodez commented
> Hey there! Sorry but I have been away from the keyboard due to vacations 😉 I'm now back to work and ready to start reviewing this on tomorrow!

Hello, Great ! 
I hope you are well rested. 

I took the opportunity to fix/improve some commits.

2025-01-07 12:12 UTC, lbroudoux commented on src/Microcks.Testcontainers/MicrocksAsyncMinionBuilder.cs
> +    public const int MicrocksAsyncMinionHttpPort = 8081;
I saw you previously used a `ushort` type for the port in `MicrocksBuilder`. Is there any difference?

2025-01-07 12:16 UTC, lbroudoux commented on src/Microcks.Testcontainers/MicrocksAsyncMinionBuilder.cs
> +            { "ASYNC_PROTOCOLS", $",{string.Join(",", _extraProtocols)}" },
Not sure why you would need a leading `$` here? Is it a way to say that this dictionary entry may already exist?

2025-01-07 12:24 UTC, lbroudoux commented on src/Microcks.Testcontainers/MicrocksContainerEnsemble.cs
> +public class MicrocksContainerEnsemble : IAsyncDisposable
Wasn't it possible to follow the `DockerContainer` contract like in `MicrocksContainer.cs`? What is actually an `IAsyncDisposable`? Can you help me understand this providing some pointers?

2025-01-07 12:26 UTC, lbroudoux commented on src/Microcks.Testcontainers/MicrocksContainerExtensions.cs
> +    public static async Task<List<UnidirectionalEvent>> GetEventMessagesForTestCaseAsync(this MicrocksContainer container,
Oh! You already implemented this! 👍

2025-01-07 12:29 UTC, lbroudoux commented on tests/Microcks.Testcontainers.Tests/Async/Kafka/KafkaContainerHelper.cs
> +public static class KafkaContainerHelper
I assume that stuffs from this package comes because the official `KafkaContainer` in Testcontainers cannot expose Kafka on more than one network port? Shouldn't we put this class in `/src` instead of `/tests` to make is distributable while the enhancement is not integrated into Testcontainers? WDYT?

2025-01-07 12:31 UTC, lbroudoux commented on tests/Microcks.Testcontainers.Tests/Async/MicrocksAsyncFeatureTest.cs
> +public sealed class MicrocksAsyncFeatureTest : IAsyncLifetime
`MicrocksAsyncKafkaMockingFunctioanilityTest.cs` for a better consistency no?

2025-01-07 12:33 UTC, lbroudoux requested changes
Looks very good as usual. Made a few comments and change requests but it's more for my own understanding of for consistency concerns. Great job! 👏

2025-01-07 22:27 UTC, SebastienDegodez commented on src/Microcks.Testcontainers/MicrocksAsyncMinionBuilder.cs
> +    public const int MicrocksAsyncMinionHttpPort = 8081;
Oh, yes, int is overkill for a port number and it also includes negative numbers, which are not valid for port numbers.

2025-01-07 22:40 UTC, SebastienDegodez commented on src/Microcks.Testcontainers/MicrocksAsyncMinionBuilder.cs
> +            { "ASYNC_PROTOCOLS", $",{string.Join(",", _extraProtocols)}" },
It's a string composition.

I could have written verbosely: 
string.Format(",{0}", string.Join(",", _extraProtocols))


https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

2025-01-10 09:57 UTC, lbroudoux commented on tests/Microcks.Testcontainers.Tests/Async/MicrocksAsyncFeatureTest.cs
> +public sealed class MicrocksAsyncFeatureTest : IAsyncLifetime
Can be changed later on. I'll mark this one as solved to I can merge it.

2025-01-10 09:57 UTC, lbroudoux commented on src/Microcks.Testcontainers/MicrocksContainerEnsemble.cs
> +public class MicrocksContainerEnsemble : IAsyncDisposable
Can be changed later on. I'll mark this one as solved to I can merge it.

2025-01-10 09:58 UTC, lbroudoux commented on tests/Microcks.Testcontainers.Tests/Async/Kafka/KafkaContainerHelper.cs
> +public static class KafkaContainerHelper
Can be changed later on. I'll mark this one as solved to I can merge it.

2025-01-10 09:58 UTC, lbroudoux approved these changes
Looks all good to me! I still have a few questions but they can be solved later on.

2025-01-10 09:59 UTC, merged